### ISSUE TITLE
Latest update to textlif creates garbage in file

### ISSUE THREAD

**Issue by isene** [bug400/lifutils#1]
Latest update to textlif gives garbage in lif file.

I do this:

`$ echo "ABC" | textlif -r 0 A | lifput cl_update.lif ; lifget cl_update.lif A | liftext`

and get this:

`liftext: Unexpected end of file 
        %9 ABCÿÿ`

**Comment by bug400** [comment]
Use the -r flag in lifget. All filters that convert HP file formats into readable format use raw files without the lif header. So this will work:
`echo "ABC" | textlif -r 0 A | lifput cl_update.lif ; lifget -r cl_update.lif A | liftext`
You may use the `lifraw` filter instead as well:
`echo "ABC" | textlif -r 0 A | lifput cl_update.lif ; lifget cl_update.lif A | lifraw |liftext`
