### ISSUE TITLE
Trojan:Win32/Zpevdo.A in the lifutils-win64-setup.exe

### ISSUE THREAD

**Issue by uliatgithub** [bug400/lifutils#5]
After I downloaded the lifutils-win64-setup.exe for Win64 the Windows Defender popped with a Virus Warning: Trojan:Win32/Zpevdo.A

**Comment by bug400** [comment]
I'll investigate this urgent. The 1.7.10 Windows executables were removed. Please try the executables of the previous version. Sorry for any inconvenience.

**Comment by bug400** [comment]
New built installs without defender warnings
