### ISSUE TITLE
I can compile lifutils, but can't mount/read a LIF formatted disk

### ISSUE THREAD

**Issue by Kevin-McKee** [bug400/lifutils#6]
Hi, I'm not sure if you'd be able to help with this, but I'm trying to copy a LIF formatted disk.  I'm able to compile and install your lifutils, but the problem is anytime I put a floppy in my drive the kernel or OS is showing messages like this

[  807.767845] usb 1-1: new full-speed USB device number 7 using xhci_hcd
[  807.971478] usb 1-1: New USB device found, idVendor=0644, idProduct=0000, bcdDevice= 0.00
[  807.971481] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  807.971483] usb 1-1: Product: TEAC FD-05PUB   
[  807.971485] usb 1-1: Manufacturer: TEAC    
[  807.974638] usb-storage 1-1:1.0: USB Mass Storage device detected
[  807.974890] scsi host4: usb-storage 1-1:1.0
[  812.219596] scsi 4:0:0:0: Direct-Access     TEAC     FD-05PUB         3000 PQ: 0 ANSI: 0 CCS
[  812.220294] sd 4:0:0:0: Attached scsi generic sg1 type 0
[  812.251178] sd 4:0:0:0: Power-on or device reset occurred
[  812.411479] sd 4:0:0:0: [sdc] Read Capacity(10) failed: Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[  812.411485] sd 4:0:0:0: [sdc] Sense Key : Medium Error [current] 
[  812.411489] sd 4:0:0:0: [sdc] Add. Sense: Cannot read medium - unknown format
[  812.411496] sd 4:0:0:0: [sdc] 0 512-byte logical blocks: (0 B/0 B)
[  812.411500] sd 4:0:0:0: [sdc] 0-byte physical blocks
[  812.443296] sd 4:0:0:0: [sdc] Write Protect is off
[  812.443301] sd 4:0:0:0: [sdc] Mode Sense: 00 46 94 00
[  812.475369] sd 4:0:0:0: [sdc] No Caching mode page found
[  812.475377] sd 4:0:0:0: [sdc] Assuming drive cache: write through
[  812.699535] sd 4:0:0:0: [sdc] Read Capacity(10) failed: Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[  812.699542] sd 4:0:0:0: [sdc] Sense Key : Medium Error [current] 
[  812.699546] sd 4:0:0:0: [sdc] Add. Sense: Cannot read medium - unknown format
[  812.859203] sd 4:0:0:0: [sdc] Attached SCSI removable disk
[  812.987408] sd 4:0:0:0: [sdc] tag#0 access beyond end of device
[  812.987416] print_req_error: 4 callbacks suppressed
[  812.987420] blk_update_request: I/O error, dev sdc, sector 2 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  812.987435] EXT4-fs (sdc): unable to read superblock
[  813.051693] sd 4:0:0:0: [sdc] tag#0 access beyond end of device
[  813.051705] blk_update_request: I/O error, dev sdc, sector 2 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  813.051721] EXT4-fs (sdc): unable to read superblock
[  813.115678] sd 4:0:0:0: [sdc] tag#0 access beyond end of device
[  813.115690] blk_update_request: I/O error, dev sdc, sector 2 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  813.115706] EXT4-fs (sdc): unable to read superblock
[  813.179441] sd 4:0:0:0: [sdc] tag#0 access beyond end of device
[  813.179452] blk_update_request: I/O error, dev sdc, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  813.179466] SQUASHFS error: squashfs_read_data failed to read block 0x0
[  813.179471] unable to read squashfs_super_block

so any of the LIF commands I try to run tell me that the device is invalid.  If I use a non-LIF formatted disk, I'm able to mount the disk and read the contents, so I know that my hardware and OS are capable.  

Any ideas how I can get past the OS not recognizing the disk and allowing me to mount it so the LIF commands will work?

**Comment by cwh42** [comment]
[tutorial.html](https://github.com/bug400/lifutils/blob/master/doc/tutorial.html) says: "USB floppy disk drives will definitely not work."

**Comment by bug400** [comment]
USB floppy drives are determined to the IBM PC physical format and do not allow any changes. You need an old floppy disk controller to read or write HP-LIF formatted disks. See the tutorial for details.

**Comment by Kevin-McKee** [comment]
OK thanks


Kevin McKee
Application Development Architect
Goodyear Canada Inc.
388 Goodyear Rd, Napanee, ON  K7R 3L2
phone.613.354.7850
krmckee@goodyear.com
