### ISSUE TITLE
Summation symbol in xfncx.xrom file causing error

### ISSUE THREAD

**Issue by CraigBladow** [bug400/lifutils#9]
There is a summation character in the xfncx.xrom file provided with lifutils.  Line 57, "25 56 ∑REG?" causes this error. Replacing it with   "25 56 SREG?" made it work.

**Comment by bug400** [comment]
Thanks for reporting this issue. I had tried a long time ago to use UTF characters to come close to the HP-41 character set. Thus I have to check for further problems of this kind. In what program of the lifutils the error occurred?

**Comment by CraigBladow** [comment]
> Thanks for reporting this issue. I had tried a long time ago to use UTF characters to come close to the HP-41 character set. Thus I have to check for further problems of this kind. In what program of the lifutils the error occurred?

The error occurs in comp41.

**Comment by bug400** [comment]
Fixed in 2.0.0
